Checking Accounts Visualization
mariaefOT/digital-bank-upcamp pull request #2
Opened 2022-09-06 17:14 UTC by mariaefOT

- Adds Cards and CheckingCards components.
- Adds unit test to this components.
- Shows the components.
- Documentation.

2022-09-08 12:13 UTC, santiago-abstracta requested changes
Accounts are rendered as expected! 🎉 

Read the comments below to improve certain aspects that could make components **less legible** and **hard to maintain**.

2022-09-08 12:13 UTC, ghost commented on src/App.js
>  function App() {
The rest of your functional components are declared using the arrow function syntax. I suggest you do the same here to keep your code consistent.

2022-09-08 12:13 UTC, ghost commented on src/App.test.js
>  });
This test isn't necessary. You only need to create tests to check that the feature you worked on works properly.

2022-09-08 12:13 UTC, ghost commented on src/components/Cards.js
> +const Cards = (props) => {
This component is in charge of rendering the specified props in only one card, so its name should be _Card_ instead of _Cards_.

2022-09-08 12:13 UTC, ghost commented on src/components/Cards.js
> +const Cards = (props) => {
Also, its name suggests that it could be reusable. You can either rename it to `AccountCard` - thus making it more domain-specific  - or remove `Card.Text` content and handle data in the `CheckingCards` component to avoid linking your `Card` component to only one use case.

2022-09-08 12:13 UTC, ghost commented on src/components/CheckingCards.js
> +import React, {useEffect, useState} from 'react';
As mentioned in the previous PR, it's not necessary to `import React from 'react';`.

2022-09-08 12:13 UTC, ghost commented on src/components/CheckingCards.js
> +import Col from 'react-bootstrap/Col';
You can use [named imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) to import these two in one line.

2022-09-08 12:13 UTC, ghost commented on src/components/CheckingCards.js
> +    const [token, setToken] = useState([]);
This shouldn't be here because that's not `CheckingCards` responsibility.

2022-09-08 12:13 UTC, ghost commented on src/components/CheckingCards.js
> +    const [account, setAccount] = useState([]);
I suggest you make it plural. Remember that the Checking Accounts endpoint can return several accounts.

2022-09-08 12:13 UTC, ghost commented on src/components/CheckingCards.js
> +    };
This one should be in the Axios config file.

2022-09-08 12:13 UTC, ghost commented on src/components/CheckingCards.js
> +    };
I suggest you create a folder named `api` and a file named `index.js` to export functions that handle these API calls, so that you can easily call them wherever and whenever you want and avoid duplicate code.

2022-09-08 12:13 UTC, ghost commented on src/components/CheckingCards.js
> +    }
I'd go for a simpler option: remove this function and just `map()` + `render()` in line 61.

2022-09-08 12:13 UTC, ghost commented on src/pages/ViewChecking.js
> +            <h1 style={{ backgroundColor: 'white', marginBottom: '20px', fontSize: 'calc(19px + 2vmin)'}}>View Checking Accounts</h1>
I suggest you create the corresponding CSS file to style this element.

2022-09-08 12:13 UTC, ghost commented on src/components/CheckingCards.test.js
> +import React from "react";
Same comment regarding the `import`.

2022-09-08 12:13 UTC, ghost commented on src/components/Cards.test.js
> +import React from "react";
Same comment regarding the `import`.

2022-09-08 12:13 UTC, santiago-abstracta commented on src/components/Cards.test.js
> +        component.getByText(props.name);
You should add more assertions. You can use the `getByText()` method to get the account type, interest rate, etc., and then add an assertion for each text. 

Example: 

```
const accountName = component.getByText(props.name);

expect(accountName).toEqual(props.name);
```

Try to see what happens when they're not equal.

2022-09-08 12:13 UTC, santiago-abstracta commented on src/components/CheckingCards.js
> +    const [account, setAccount] = useState([]);
BTW, this should go in `ViewChecking`, so that you can then pass data through props.

2022-09-08 12:13 UTC, santiago-abstracta commented on src/components/CheckingCards.test.js
> +        const component = render(<CheckingCards/>);
CheckingCards should be able to receive an array of accounts. That way you could create an array here, pass it through props and do something similar to what you did in the other test.

2022-09-08 13:44 UTC, mariaefOT commented on src/App.js
>  function App() {
Thanks, I had missed that the app was not defined with arrow functions.

2022-09-12 20:03 UTC, santiago-abstracta approved these changes

2022-09-12 20:16 UTC, merged