User registration
mariaefOT/digital-bank-upcamp pull request #7
Opened 2022-10-24 17:15 UTC by mariaefOT

- Visual modification to the login
- Added user registration component
- Added user registration unit tests

2022-10-24 20:12 UTC, santiago-abstracta requested changes

2022-10-24 20:12 UTC, ghost commented on src/App.js
> +import CreateUser from './pages/CreateUser';
Read the following comment made in a Reddit thread regarding naming conventions for React Components:

> Since components represent modular front-end pieces, I’d say they need to be nouns. Like `CardView`, `AnnouncementCarousel` or `PageView`.
You may be tempted to name a component after the functionality it runs to render itself, such as incorrectly naming `CardView` as `RenderCard`. Just remember that “rendering cards” is simply the action that the `CardView` component performs in order to saturate it’s data.

2022-10-24 20:12 UTC, ghost commented on src/App.js
> +              <Route path="/createUser" element={<CreateUser />}/>
These are common paths you can use:

/user/create 

or 

/user/register

2022-10-24 20:12 UTC, ghost commented on src/CSS/UserRegistration.css
> +.form-sub-title {
form-subtitle*

2022-10-24 20:12 UTC, ghost commented on src/pages/CreateUser.js
> +import UserRegistration from "../components/UserRegistration";
What about `SignUpCard` or `SignUpForm`?

2022-10-24 20:12 UTC, ghost commented on src/pages/CreateUser.js
> +const CreateUser = () => {
I think `SignUpPage` would be an ideal name for this one.

2022-10-24 20:12 UTC, ghost commented on src/pages/CreateUser.js
> +            </h1>
This can be your `Logo` component.

2022-10-24 20:12 UTC, ghost commented on src/pages/LoginPage.js
> +                </h1>
You can avoid repetition by creating a `Logo` component.

2022-10-24 20:12 UTC, ghost commented on src/pages/LoginPage.js
> +                    Don't have account?
... have an account?

2022-10-24 20:12 UTC, ghost commented on src/components/UserRegistration.js
> +        login({username:'admin@demo.io', password:'Demo123!'});
Credentials should be stored in an `env` file for security reasons. In this case, you can create a separate file to call the credentials object from there, but take that into account for future (and real) projects ;)

2022-10-24 20:12 UTC, santiago-abstracta commented on src/components/UserRegistration.js
> +        if (form.checkValidity() === false) {
You can do it like this: `!form.checkValidity()`.

2022-10-24 20:12 UTC, santiago-abstracta commented on src/components/UserRegistration.js
> +            };
These lines aren't necessary. You can just pass the `values` object as a parameter to the `createNewUser` function.

2022-10-25 14:10 UTC, santiago-abstracta requested changes

2022-10-25 14:10 UTC, ghost commented on src/components/UserRegistration.js
> +                        </Form.Group>
I'd split these form controls into small pieces (components) because this component is too big.

This form control could be a `FormTitleField` or `TitleField` component.

2022-10-25 14:10 UTC, santiago-abstracta commented on src/components/UserRegistration.js
> +                        </Form.Group>
These are almost the same. You can create a `FormNameField` or `NameField` to handle both first and last names.

2022-10-25 14:10 UTC, santiago-abstracta commented on src/components/UserRegistration.js
> +                        </Form.Group>
You can create a `FormGenderField` or `GenderField` here.

2022-10-25 14:10 UTC, santiago-abstracta commented on src/components/UserRegistration.js
> +                        </Form.Group>
You can probably create a generic `FormInputField` to handle first name, last name, date of birth, and SSN.

2022-10-25 14:10 UTC, santiago-abstracta commented on src/components/UserRegistration.js
> +                        </Form.Group>
The same comment applies to most of the fields that come after line 199.

2022-10-25 14:26 UTC, santiago-abstracta requested changes

2022-10-25 14:26 UTC, santiago-abstracta commented on src/tests/UserRegistration.test.js
> +    it('Should render the user registration form when the Create user page is loaded', () => {
In this case, "Should render the User Registration form" is enough.

2022-10-25 14:26 UTC, ghost commented on src/tests/UserRegistration.test.js
> +    it('Should onSubmit is called when all fields pass validation', () => {
Should submit the form when all fields are valid...*

2022-10-25 14:26 UTC, ghost commented on src/tests/UserRegistration.test.js
> +        const dropdownTitle = screen.getByRole('combobox', {name: /title/i });
titleDropdown*

2022-10-25 14:26 UTC, ghost commented on src/tests/UserRegistration.test.js
> +        user.type(inputSocialSecurityNumber, '12/10/2000');
Remember that the name of the element should go after the name of the field. E.g. _firstNameInput_ (not _inputFirstName_).

2022-10-25 14:26 UTC, ghost commented on src/tests/UserRegistration.test.js
> +        const checkboxTerms = screen.getByRole('checkbox', {name: /agree the terms and policy/i });
Same comment as before.

2022-10-25 14:26 UTC, ghost commented on src/tests/UserRegistration.test.js
> +    it('It should display form incomplete alert', () => {
The "It" is extra.

2022-10-25 14:26 UTC, ghost commented on src/tests/UserRegistration.test.js
> +    it('You should return to the previous page of the form when pressing the previous button', () => {
The "You" is extra. `it` specifications should start with the word "should".

2022-10-25 15:00 UTC, mariaefOT commented on src/App.js
> +import CreateUser from './pages/CreateUser';
Thanks. I already applied it to all views.

2022-10-26 13:43 UTC, santiago-abstracta requested changes

2022-10-26 13:43 UTC, santiago-abstracta commented on src/pages/LoginView.js
> +                    Have an account?
The "Don't" part was ok, you just needed to change the last part of the question.

2022-10-26 13:43 UTC, santiago-abstracta commented on src/data/credentials.js
> +export const credentialsAdmin = {
adminCredentials*

2022-10-26 13:43 UTC, santiago-abstracta commented on src/tests/SignUpForm.test.js
> +    it('Should submit the form when all fields are valid...', () => {
The three dots aren't necessary. What I meant in my comment was that you could add something else after the suggested message.

2022-10-26 18:10 UTC, santiago-abstracta approved these changes

2022-10-26 18:50 UTC, merged